Fix "TypeError: %d format: a number is required, not IntegrityError"
Error occurs at `tmlibrary/tmlib/models/utils.py` line 477.

Sample traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not IntegrityError
Logged from file utils.py, line 477
```