Fix "TypeError: %d format: a number is required, not NoneType"
This error would occur when it is not possible to retrieve the
specified "mapobject" because of a DB error, then `self.id` is `None`.

Sample traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File ".../TissueMAPS/tmlibrary/tmlib/models/mapobject.py", line 395, in __repr__
    return '<MapobjectType(id=%d, name=%r)>' % (self.id, self.name)
TypeError: %d format: a number is required, not NoneType
```