Raise an HTTP 404 error from API calls if the given experiment does not exist.
This should prevent errors like:

        AttributeError: 'NoneType' object has no attribute 'workflow_description'

where the code retrieves an experiment using `session.query()` but
never checks if *something* was actually returned...

Likely, a similar patch should be made for all the other REST API
calls in other modules, but I didn't check yet...