Bump dependency on FITS-tools to 0.0dev282.
Version 0.0dev258 is no longer installable; `pip install` dies with
the following traceback::

```
Collecting FITS-tools==0.0.dev258 (from -r /home/tissuemaps/tmlibrary/requirements.txt (line 11))
  Downloading FITS_tools-0.0.dev258.tar.gz (207kB)
    Complete output from command python setup.py egg_info:
    git submodule command failed unexpectedly:
    fatal: Not a git repository (or any of the parent directories): .git

    Traceback (most recent call last):
      File  "<string>" line 1, in <module>
      File  "/tmp/pip-build-d98xFW/FITS-tools/setup.py" line 8, in <module>
        import ah_bootstrap
      File  "ah_bootstrap.py" line 748, in <module>
        _main()
      File  "ah_bootstrap.py" line 745, in _main
        use_astropy_helpers(**kwargs)
      File  "ah_bootstrap.py" line 249, in use_astropy_helpers
        upgrade = _do_upgrade(dist, index_url)
      File  "ah_bootstrap.py" line 340, in _do_upgrade
        major, minor = (int(part) for part in dist.parsed_version[:2])
    TypeError: 'Version' object has no attribute '__getitem__'
```