Change input from files to directory
Using list of files as input argument created problems with larger
projects, because there are too many files leading to the following
error: 'Argument list too long'.