Revert "Rely on the DB's "ON DELETE CASCADE" settings to delete "map objects"."
This reverts commit 4e564b54b8975a20fe7e76aaa3061ee9163afccb,
which seems to make Jterator jobs fail with the following error:

```
JOB FAILED:
'Integer' object has no attribute '__table__'
  File "/home/tissuemaps/TissueMAPS/tmlibrary/tmlib/workflow/cli.py", line 293, in __main__
    cli_instance(arguments)
  File "/home/tissuemaps/TissueMAPS/tmlibrary/tmlib/workflow/cli.py", line 352, in __call__
    method(**method_args)
  File "/home/tissuemaps/TissueMAPS/tmlibrary/tmlib/workflow/cli.py", line 383, in init
    api.delete_previous_job_output()
  File "/home/tissuemaps/TissueMAPS/tmlibrary/tmlib/workflow/jterator/api.py", line 233, in delete_previous_job_output
    filter(~tm.MapobjectType.name.in_(static_types)).\
  File "/home/tissuemaps/TissueMAPS/tmlibrary/tmlib/models/utils.py", line 312, in delete
    if cls.__table__.info['is_distributed']:
```