Ensure that the path to the setup file is absolute.
Fixes an error occurring in task "Refresh dynamic inventory" in the
"launch" playbook, where you get a message like::

        OSError: Setup file "etc/cluster_setup_os.yml" does not exist!