Do not throw error if deleting a non-existing experiment.
Avoid errors like the following::

         [  4473] 2018-03-20 11:28:18 | INFO     | tmserver.api.experiment                  | delete experiment 3
         [  4473] 2018-03-20 11:28:18 | INFO     | tmlib.models.utils                       | drop schema of experiment 3
         Traceback (most recent call last):
           ...
           File "/home/tissuemaps/tmserver/tmserver/api/experiment.py", line 413, in delete_experiment
             filter_by(id=experiment_id).\
           File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 359, in delete
             _drop_schema(connection, schema)
           File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 177, in _drop_schema
             cursor.execute('DROP SCHEMA %s CASCADE;' % schema_name)
         psycopg2.ProgrammingError: schema "experiment_3" does not exist