Fix "TypeError: delete() got an unexpected keyword argument 'synchronize_session'" in `experiment.py` line 431
As it turns out, we're getting TM's own customized `Query()` object
which overrides a few methods from SQLAlchemy's `Session.Query`
object, including `.delete()` with an incompatible signature...