Fix PostGreSQL error "function polygon(record) does not exist".
The SQL error is unfortunately not visible in logs; one has to
manually run the SQL query in `psql` to see the real cause of the
problem.  All that is shown in the logs is this rather cryptic message:

    sqlalchemy.exc.InternalError: (psycopg2.InternalError) failed to execute task 2
     [SQL: 'SELECT mapobject_segmentations.mapobject_id AS mapobject_segmentations_mapobject_id, ST_AsGeoJSON(ST_SimplifyPreserveTopology(mapobject_segmentations.geom_polygon, %(ST_SimplifyPreserveTopology_1)s)) AS "ST_AsGeoJSON_1" \nFROM mapobject_segmentations \nWHERE mapobject_segmentations.segmentation_layer_id = %(segmentation_layer_id_1)s AND ST_Intersects(mapobject_segmentations.geom_polygon, %(ST_Intersects_1)s)'] [parameters: {'ST_Intersects_1': 'POLYGON((17152 -6400, 16896 -6400, 16896 -6144, 17152 -6144, 17152 -6400))', 'segmentation_layer_id_1': 10, 'ST_SimplifyPreserveTopology_1': 1}] (Background on this error at: http://sqlalche.me/e/2j85)